language: objective-c
osx_image: xcode6.4
xcode_workspace: FoodTracker.xcworkspace
before_install:
  - gem update --system
  - gem update bundler
  - bundle install
  - bundle exec pod install
script:
  - make test
